name: build

on:
  push:
    branches: [ "main", "build" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
  ContinuousIntegrationBuild: true
  RestoreLockedMode: true
  Configuration: Release
  VersionSuffix: preview${{ github.run_id }}

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore

    - name: test
      run: dotnet test --no-build --no-restore

    - name: pack
      run: dotnet pack --no-build --no-restore -o dist

    - name: publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: VbaCompression_${{ env.VersionSuffix }}
        path: '${{ github.workspace }}/dist'
