name: labels

on:
  push:
    branches: main
    paths:
      - '.github/labels.json'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gitlabels/gitlabels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
