name: release

on:
  push:
    branches: "build"
    tags: [ 'v*.*.*' ]

permissions:
  contents: read

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
  ContinuousIntegrationBuild: true
  RestoreLockedMode: true
  Configuration: Release
  RepositoryBranch: '${{ github.ref_name }}'
  RepositoryCommit: '${{ github.sha }}'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore

    - name: test
      run: dotnet test --no-build --no-restore

    - name: pack
      run: dotnet pack --no-build --no-restore -o dist

    - name: publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: VbaCompression_build_${{ github.run_id }}
        path: '${{ github.workspace }}/dist'
